# Generated by Django 3.2.4 on 2021-07-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='Battle_picture/')),
                ('description', models.FileField(blank=True, null=True, upload_to='Battle_description/')),
            ],
        ),
        migrations.CreateModel(
            name='Technics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='Technics_picture/')),
                ('description', models.FileField(blank=True, null=True, upload_to='Technics_description/')),
                ('chakra', models.CharField(blank=True, choices=[('Ве', 'Ветер'), ('Мо', 'Молнии'), ('Ог', 'Огонь'), ('Во', 'Вода'), ('Зе', 'Земля')], default='Ве', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='Villages_picture/')),
                ('description', models.FileField(blank=True, null=True, upload_to='Villages_description/')),
            ],
        ),
        migrations.CreateModel(
            name='Shinobi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='Shinobi_picture/')),
                ('description', models.FileField(blank=True, null=True, upload_to='Shinobi_description/')),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.battle')),
                ('technics', models.ManyToManyField(to='wiki.Technics')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.village')),
            ],
        ),
    ]
