# Generated by Django 3.2.4 on 2021-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shinobi',
            name='battle',
        ),
        migrations.AddField(
            model_name='shinobi',
            name='battle',
            field=models.ManyToManyField(to='wiki.Battle'),
        ),
    ]
