# Generated by Django 3.2.4 on 2021-07-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20210727_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technics',
            name='chakra',
        ),
    ]
